[tool.poetry]
name = "hubitatcontrol"
version = "0.7"
description = "Hubitat Maker API Interface"
authors = ["Jesse Schoepfer <jelloeater@gmail.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "*"


[tool.poetry.group.dev.dependencies]
setuptools = "*"
mypy = "*"
vulture = "*"
isort = "*"
pytest = "*"
pytest-cov = "*"
pytest-pycharm = "*"
python-dotenv = "*"
pdoc3 = "*"
radon = "*"
xenon = "*"
bandit = "*"
black = "*"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
