[tool.poetry]
name = "hubitatcontrol"
version = "0.7"
description = ""
authors = ["Jesse Schoepfer <jelloeater@gmail.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "*"


[tool.poetry.group.dev.dependencies]
flit = "*"
isort = "*"
pytest = "*"
pytest-cov = "*"
pytest-pycharm = "*"
python-dotenv = "*"
pdoc3 = "*"
pylint = "*"
radon = "*"
xenon = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
