version: '3'
vars:
  BUILD_DIR: hubitatcontrol
tasks:
    default:
        - task: test
        - task: build
    setup:
        - python3 -m pip install pipx
        - python3 -m pipx ensurepath
        - pipx install poetry
    clean:
        - rm -rf dist
        - poetry cache clear _default_cache --all  --no-interaction
        - poetry cache clear PyPI --all  --no-interaction
    build:
        env:
            PIPENV_IGNORE_VIRTUALENVS: 1
        cmds:
            - poetry check
            - poetry install
            - poetry show
            - task: docs
            - poetry build
    docs:
        - rm -rf docs
        - poetry run pdoc3 hubitatcontrol -o docs -f
        - poetry run pyreverse hubitatcontrol -d docs
        - git add docs
    test:
        silent: false
        interactive: true
        cmds:
            - poetry install
            - poetry run isort --diff .
            - poetry run pytest --cov
            - poetry run xenon --max-absolute B --max-modules B --max-average B {{.BUILD_DIR}}
            - poetry run radon mi {{.BUILD_DIR}}
    cc:
        env:
            PIPENV_VERBOSITY: -1
            PIPENV_IGNORE_VIRTUALENVS: 1
        cmds:
            - poetry run radon raw {{.BUILD_DIR}}
            - poetry run radon hal {{.BUILD_DIR}}
            - poetry run radon cc {{.BUILD_DIR}} -a
            - poetry run radon mi {{.BUILD_DIR}}
#    wily:
#        - pipenv run wily clean -y
#        - pipenv run wily build {{.BUILD_DIR}}
#        - pipenv run wily rank {{.BUILD_DIR}} mi --threshold=50
#        - pipenv run wily rank {{.BUILD_DIR}} complexity --threshold=15
#        - pipenv run wily rank {{.BUILD_DIR}} rank
    install:
        - flit install --user
    uninstall:
        - pip uninstall hubitatcontrol -y
