version: '3'
tasks:
    default:
        - task: test
        - task: build
    clean:
        - pipenv clean
    build:
        cmds:
            - pipenv install
            - pipenv graph
            - pipenv run flit build
    test:
        silent: false
        interactive: true
        env:
            PIPENV_VERBOSITY: -1
        cmds:
            - pip install pipenv
            - pipenv install --dev
            - pipenv run isort --recursive --diff .
            - pipenv run pytest --cov
    install:
        - task: build
        - deactivate
        - flit install --user
