version: '3'
vars:
  BUILD_DIR: hubitatcontrol
tasks:
    default:
        - task: test
        - task: build
    clean:
        - pipenv clean
        - rm -rf dist
    build:
        env:
            PIPENV_IGNORE_VIRTUALENVS: 1
        cmds:
            - pipenv install
            - pipenv graph
            - task: docs
            - pipenv run flit build
    docs:
        - rm -rf docs
        - pipenv run pdoc3 hubitatcontrol -o docs -f
        - pipenv run pyreverse hubitatcontrol -d docs
        - git add docs
    test:
        silent: false
        interactive: true
        cmds:
            - pip install pipenv
            - pipenv install --dev
            - pipenv run isort --diff .
            - pipenv run pytest --cov
            - pipenv run xenon --max-absolute B --max-modules B --max-average B {{.BUILD_DIR}}
            - pipenv run radon mi {{.BUILD_DIR}}
    cc:
        env:
            PIPENV_VERBOSITY: -1
            PIPENV_IGNORE_VIRTUALENVS: 1
        cmds:
            - pipenv run radon raw {{.BUILD_DIR}}
            - pipenv run radon hal {{.BUILD_DIR}}
            - pipenv run radon cc {{.BUILD_DIR}} -a
            - pipenv run radon mi {{.BUILD_DIR}}
#    wily:
#        - pipenv run wily clean -y
#        - pipenv run wily build {{.BUILD_DIR}}
#        - pipenv run wily rank {{.BUILD_DIR}} mi --threshold=50
#        - pipenv run wily rank {{.BUILD_DIR}} complexity --threshold=15
#        - pipenv run wily rank {{.BUILD_DIR}} rank
    install:
        - flit install --user
    uninstall:
        - pip uninstall hubitatcontrol -y
