version: '3'
tasks:
    default:
        - task: test
        - task: build
    build:
        cmds:
            - pipenv clean
            - pipenv install
            - pipenv graph
            - pipenv run flit build
    test:
        silent: false
        interactive: true
        env:
            PIPENV_VERBOSITY: -1
        cmds:
            - pip install pipenv
            - pipenv install --dev
            - pipenv run pytest --cov
