version: '3'
tasks:
    default:
        - task: test
        - task: build
    clean:
        - pipenv clean
        - rm -rf dist
    build:
        env:
            PIPENV_IGNORE_VIRTUALENVS: 1
        cmds:
            - pipenv install
            - pipenv graph
            - pipenv run pdoc3 hubitatcontrol -o docs -f
            - pipenv run flit build
    test:
        silent: false
        interactive: true
        env:
            PIPENV_VERBOSITY: -1
        cmds:
            - pip install pipenv
            - pipenv install --dev
            - pipenv run isort --diff .
            - pipenv run pytest --cov
    install:
        - flit install --user
    uninstall:
        - pip uninstall hubitatcontrol -y
