version: '3'
vars:
    BUILD_DIR: hubitatcontrol
    IMAGE_NAME: hubitatcontrol
    DOCKER_FILE: Dockerfile
tasks:
    default:
        silent: true
        interactive: false
        cmds:
            - poetry install
            - task: format
            - task: test
    setup:
        - python3 -m pip install pipx
        - python3 -m pipx ensurepath
        - pipx install poetry
        - task: install-hooks
    clean:
        - rm -rf dist
        - poetry cache clear _default_cache --all  --no-interaction
        - poetry cache clear PyPI --all  --no-interaction
        - poetry check
        - py3clean .
    format:
        silent: true
        interactive: false
        cmds:
            - poetry run isort --atomic {{.BUILD_DIR}}
            - poetry run black {{.BUILD_DIR}} --color #--diff
    test:
        silent: true
        interactive: false
        cmds:
            - poetry run bandit --silent -r {{.BUILD_DIR}}
            - poetry run vulture --min-confidence 100 {{.BUILD_DIR}}
            - poetry run xenon --max-absolute B --max-modules B --max-average B {{.BUILD_DIR}}
            - poetry run pytest --cov --cov-fail-under=80 #--typeguard-packages={{.BUILD_DIR}} # Leave typeguard off for now
    docs:
        - rm -rf docs
        - poetry run pdoc3 {{.BUILD_DIR}} -o docs -f
        - poetry run pyreverse {{.BUILD_DIR}} -d docs
        - git add docs
    commit:
        - task: format
        - task: docs
    build:
        env:
            PIPENV_IGNORE_VIRTUALENVS: 1
        deps: [docs, clean]
        cmds:
            - poetry build
    install-hooks:
        cmds:
            - poetry run pre-commit install
    remove-hooks:
        ignore_error: true
        cmds:
            - poetry run pre-commit uninstall
            - rm .git/hooks -rf
    docker:
        desc: Build and run Docker image
        cmds:
            - task: clean
            - docker build . -t {{.IMAGE_NAME}}:latest -f {{.DOCKER_FILE}}
            - docker run --env-file .env --rm --name {{.IMAGE_NAME}} {{.IMAGE_NAME}}:latest
