name: Test

on:
    pull_request: { }
    push:
        branches: [ main ]
        tags: [ "*" ]
#    workflow_dispatch:
jobs:
    test:
        runs-on: [self-hosted, linux]
        steps:
            - uses: actions/checkout@v2
            - run: tree
            - run: docker build . -t hubitat:latest
            - run: docker run -e HUBITAT_API_APP_ID=${{ secrets.HUBITAT_API_APP_ID }} -e HUBITAT_API_TOKEN=${{ secrets.HUBITAT_API_TOKEN }} -e HUBITAT_HOST=${{ secrets.HUBITAT_HOST }} --rm --name hubitat hubitat:latest
              env: # These need to be set in the repo or the builds will fail
                  HUBITAT_API_APP_ID: ${{ secrets.HUBITAT_API_APP_ID }}
                  HUBITAT_API_TOKEN: ${{ secrets.HUBITAT_API_TOKEN }}
                  HUBITAT_HOST: ${{ secrets.HUBITAT_HOST }}
