name: Test

on:
    pull_request: { }
    push:
        branches: [ main ]
        tags: [ "*" ]
#    workflow_dispatch:
jobs:
    test:
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v2
            - run: tree
            - run: |
                  python3 -m pip install pipx
                  python3 -m pipx ensurepath
                  pipx install poetry
                  poetry config virtualenvs.create false
                  poetry install
                  poetry run pytest --cov --cov-fail-under=85
              env: # These need to be set in the repo or the builds will fail
                  HUBITAT_API_APP_ID: ${{ secrets.HUBITAT_API_APP_ID }}
                  HUBITAT_API_TOKEN: ${{ secrets.HUBITAT_API_TOKEN }}
                  HUBITAT_HOST: ${{ secrets.HUBITAT_HOST }}
                  HUBITAT_CLOUD_TOKEN: ${{ secrets.HUBITAT_CLOUD_TOKEN }}
